FROM python:3.8.10
ADD index.html index.html
ADD webserver.py webserver.py
ADD game.html game.html
ADD about.html about.html
# WORKDIR C:/Users/theow/coding/my-webserver/cooler-webserver/workdirectory
# COPY about.html .
# COPY game.html .
# COPY index.html .
# COPY webserver.py .
EXPOSE 2809
CMD ["python3", "webserver.py"]
# ENTRYPOINT ["python3", "webserver.py"]