FROM python:3.8.10
WORKDIR workdirectory
COPY about.html workdirectory/about.html
COPY game.html workdirectory/game.html
COPY index.html workdirectory/index.html
COPY webserver.py workdirectory/webserver.py 
CMD ["python3 ./workdirectory/webserver.py"]